### ISSUE TITLE
Feature Request:  Integration with digest package

### ISSUE THREAD

**Issue by bms63** [atorus-research/logrx#107] opened 2022-08-02 20:30 UTC
### Feature Idea

Can we create unique hashes to show uniqueness of the programs being run?  Perhaps digest package is the way to do this? 

http://dirk.eddelbuettel.com/code/digest.html

**Comment by kodesiba** [comment] 2022-08-02 20:40
duplicate of #29

**Closed by kodesiba** 2022-08-02 20:40 UTC
Labels: duplicate
